name: iOS Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

   - name: Build and Test
      run: |
        xcodebuild test -project RutaUTP.xcodeproj -scheme RutaUTP -destination 'platform=iOS Simulator,OS=latest'
